apiVersion: apps/v1
kind: Deployment 
metadata:
  name: cloudcrush-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudcrush-api
  template:
    metadata:
      labels:
        app: cloudcrush-api
    spec:
      imagePullSecrets:
        - name: ghcr-auth
      containers:
        - name: api
          image: ghcr.io/amitp07/cloudcrush/cloudcrush-api:latest 
          imagePullPolicy: Always 
          ports:
            - containerPort: 3000
          command: ['./cloudcrush-api']
          env:
           - name: ENVIRONMENT 
             value: sandbox 
           - name: AWS_REGION
             value: us-east-1

---

apiVersion: v1
kind: Service
metadata:
  name: cloudcrush-api-svc
spec:
  selector:
    app: cloudcrush-api
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
      protocol: TCP