apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudcrush-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudcrush-api
  template:
    metadata:
      labels:
        app: cloudcrush-api
    spec:
      imagePullSecrets:
        - name: ghcr-auth
      containers:
        - name: api
          image: ghcr.io/amitp07/cloudcrush/cloudcrush-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          command: ["./cloudcrush-api"]
          env:
            - name: ENVIRONMENT
              value: production
            - name: AWS_REGION
              value: ap-south-1
            - name: NATS_DSN
              valueFrom:
                secretKeyRef:
                  name: cloudcrush-secrets
                  key: nats-dsn 
            - name: POSTGRES_DSN
              valueFrom:
                secretKeyRef:
                  name: cloudcrush-secrets 
                  key: postgres-dsn
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: cloudcrush-secrets
                  key: aws-access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudcrush-secrets
                  key: aws-secret-key
                  

---
apiVersion: v1
kind: Service
metadata:
  name: cloudcrush-api-svc
spec:
  selector:
    app: cloudcrush-api
  type: ClusterIP 
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
