apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudcrush-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      worker: cloudcrush
  template:
     metadata:
      labels:  
        worker: cloudcrush
     spec:
      containers:
        - name: cloudcrush-worker
          image: ghcr.io/amitp07/cloudcrush/cloudcrush-api:latest
          command: ["./cloudcrush-worker"]
          env:
           - name: NATS_DSN
             value: nats-svc:4222 
           - name: POSTGRES_DSN
             value: postgres://postgres:postgres@postgres-service:5432/k8s-db?sslmode=disable
           - name: AWS_IMAGE_JOB_BUCKET
             value: cloudcrush
           - name: AWS_ACCESS_KEY_ID
             value: minioadmin
           - name: AWS_SECRET_ACCESS_KEY
             value: minioadmin
           - name: AWS_ENDPOINT
             value: http://minio-svc:9000 
           - name: AWS_REGION
             value: us-east-1


        