name: CloudCrush Infrastructure

on:
  push:
    branches:
      - master
    paths:
      - k8s-infra/**
  workflow_dispatch:

jobs:
  deploy_infra:
    runs-on: ubuntu-latest
    environment: sandbox
    
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Setup nodejs
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      # install node deps using clean install
      - name: Install CDK dependencies
        run: |
          cd k8s-infra
          npm ci 
      - name: Debug Environment and Paths
        working-directory: k8s-infra
        run: |
          echo "=== Current Working Directory ==="
          pwd
          
          echo "=== List root directory ==="
          ls -F ..
          
          echo "=== List k8s-infra directory ==="
          ls -F
          
          echo "=== List bin directory ==="
          ls -F bin/
          
          echo "=== Check if ts-node exists ==="
          ls -l ./node_modules/.bin/ts-node || echo "ts-node NOT FOUND"
          
          echo "=== Check node and npm versions ==="
          node -v
          npm -v
      # start cdk configuration, synth diff and deploy
      - name: CDK Synth
        working-directory: k8s-infra
        run: ./node_modules/.bin/cdk synth --app "node_modules/.bin/ts-node --prefer-ts-exts bin/k8s-infra.ts"
      # configure aws creds using oidc
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_GITHUB_OIDC_ROLE}} 
          aws-region: ${{vars.AWS_REGION}}
      - name: CDK diff
        working-directory: k8s-infra
        run: npx cdk diff --all
      - name: CDK Deploy 
        working-directory: k8s-infra
        run: npx cdk deploy \
          --require-approval never